/**
 * This table will give more information about the whe user uses the keyboard, by mapping
 * keyboard regions - each region of physical keys receives a key
 *
 */
export const KeyRegionsStringTable = {
    'IntlBackslash': '0',
    'Digit1': '0',
    'Digit2': '0',
    'Digit3': '0',
    'Digit4': '1',
    'Digit5': '1',
    'Digit6': '1',
    'Digit7': '1',
    'Digit8': '2',
    'Digit9': '2',
    'Digit0': '2',
    'KeyQ': '3',
    'KeyW': '3',
    'KeyE': '3',
    'KeyA': '3',
    'KeyS': '3',
    'KeyD': '3',
    'KeyZ': '3',
    'KeyX': '3',
    'KeyC': '3',
    'KeyR': '4',
    'KeyT': '4',
    'KeyF': '4',
    'KeyG': '4',
    'KeyV': '4',
    'KeyB': '4',
    'KeyY': '5',
    'KeyU': '5',
    'KeyH': '5',
    'KeyJ': '5',
    'KeyN': '5',
    'KeyM': '5',
    'KeyI': '6',
    'KeyO': '6',
    'KeyP': '6',
    'KeyK': '6',
    'KeyL': '6',
    'Comma': '6',
    'Period': '6',
    'Semicolon': '7',
    'Minus': '7',
    'Equal': '7',
    'Slash': '7',
    'BracketLeft': '7',
    'Backslash': '7',
    'BracketRight': '7',
    'Quote': '7',
    'NumLock': '8',
    'NumpadDivide': '8',
    'NumpadMultiply': '8',
    'NumpadSubtract': '8',
    'NumpadAdd': '8',
    'NumpadEnter': '8',
    'NumpadDecimal': '8',
    'Numpad0': '8',
    'Numpad1': '8',
    'Numpad2': '8',
    'Numpad3': '8',
    'Numpad4': '8',
    'Numpad5': '8',
    'Numpad6': '8',
    'Numpad7': '8',
    'Numpad8': '8',
    'Numpad9': '8',
};
