name: Nightly Build

on:
  schedule:
    - cron: "0, 0, *, *, *"
      workflow_dispatch:

env:
  BUILD_REPORTS_FOLDER_PATH: ./build_reports
  TEST_REPORTS_FOLDER_PATH: ./build_reports/test_report_artifacts
  CODE_COVERAGE_REPORTS_FOLDER_PATH: ./build_reports/test_coverage_report_artifacts
  PIPELINE_SCRIPTS_PATH: ./.github/scripts
  S3_BUILDS_PATH: s3://rnd-bcdn/clientDev/js/builds
  S3_RELEASES_PATH: s3://rnd-bcdn/releases/js
  NODE_JS_VERSION: 20
  NETWORK_TIMEOUT: 100000

jobs:
  nightly_build:
    name: Nightly Build
    runs-on: [ client-runner ]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_JS_VERSION }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn Packages
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: |
          yarn --network-timeout $NETWORK_TIMEOUT
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CLIENT_TEAM_JFROG_ACCESS_TOKEN }}
      - name: Set Version Env Vars
        run: source $PIPELINE_SCRIPTS_PATH/setVersionEnvVars.sh
      - name: Run ESLINT
        run: yarn run eslint
      - name: Build Release
        run: yarn run build
      - name: Build Debug
        run: yarn run builddev
      - name: Build Obfuscated
        run: yarn run buildObfuscate
      - name: Upload Library Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: library_artifacts
          path: dist/**
          if-no-files-found: error
      - name: Upload Temp Library Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: temp_library_artifacts
          path: tempClasses/**
          retention-days: 1
          if-no-files-found: error
