export const MasterSlaveMessage = {
    dataFromSlave: 'dataFromSlave',
    registerSlave: 'registerSlave',
    logPerfSlave: 'logPerfSlave',
    updateSlaveConf: 'updateSlaveConf',
    updateSlaveState: 'updateSlaveState',
    updateMasterContext: 'updateMasterContext',
    resetSessionTriggerFromSlave: 'resetSessionTriggerFromSlave',
    mouseChallengeTriggerFromSlave: 'mouseChallengeTriggerFromSlave',
    onBeforeUnload: 'onbeforeunload',
    slaveHandShake: 'SlaveHandShake',
    cdHandShake: 'CDHandShake',
    slaveAlive: 'slaveAlive',
    iosHandshake: 'iosHandshake',
    channelMessageIdAck:'channelMessageIdAck',
    startMessagingIntervalToChannel:'startMessagingIntervalToChannel',
    isChannelSupportsAckMessageLogic: "isChannelSupportsAckMessageLogic",
};
