export MAJOR_MINOR_VERSION=2.48
export SP_VERSION=0
export MAJOR_MINOR_SP_VERSION=$MAJOR_MINOR_VERSION.$SP_VERSION
export FULL_VERSION=$MAJOR_MINOR_SP_VERSION.$GITHUB_RUN_NUMBER

export BRANCH_NAME=${GITHUB_REF##*/}

if [[ $BRANCH_NAME != "main" ]]
then
    export FULL_VERSION=$FULL_VERSION-$BRANCH_NAME
fi

echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV
echo "SHORT_VERSION=$MAJOR_MINOR_SP_VERSION" >> $GITHUB_ENV
echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
echo "COMMIT_ID=$GITHUB_SHA" >> $GITHUB_ENV
echo "BUILD_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

echo "SHORT_VERSION=$MAJOR_MINOR_SP_VERSION" >> $GITHUB_OUTPUT

echo 'SDK VERSION' $FULL_VERSION

